#lang racket/base

(require ming ming/list ming/string ming/number
         racket/format
         "rules-helper.rkt")
(provide T1 T2 T3 T4 T5 T6 T7 T8 T9 T10 T11
         VP1 VP2 VP3 VP4 VP5 VP6 VP7 VP8 VP9 VP10 VP11 VP12
         E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14
         D1 D2 D3 D4
         C1 C2 C3 C4 C5 C6 C7
         BO1 BO2 BO3 BO4 BO5 BO6
         B1 B2 B3 B4 B5 B6 B7
         S1 S2 S3 S4 S5 S6 S7 S8
         ;; R1 R2 R3 R4 R5
         )
;; 􏵞: 0707，0706，0705，0704，0703。通常需要逆序，亦即(􏾛 􏵞)

;; Table 1. Window Parameters
;; 参数	数值	说明
;; W-TREND	3	短期趋势判断
;; W-RANGE	5	横盘、压缩判断
;; W-DIV	10	结构性背离观察窗口
;; W-HIGHLOW	20	局部高低点观察窗口
;; W-CONFIRM	2	突破确认窗口

;; Trend States
(名 (T1 L)
    (并 (> (dPt L) 0)
        (> (dPt1 L) 0)))
(名 (T2 L)
    (并 (< (dPt L) 0)
        (< (dPt1 L) 0)))
(名 (T3 L)
    (并 (> (dpt L) 0)
        (> (dpt1 L) 0)))
(名 (T4 L)
    (并 (< (dpt L) 0)
        (< (dpt1 L) 0)))
(名 (T5 L)
    (并 (<= (- (maxP L 5)
               (minP L 5))
            1)
        (<= (- (maxp L 5)
               (minp L 5))
            8)))
(名 (T6 L)
    (并 (T5 L)
        (> (pt L) (maxp L 5 1))
        (> (dpt L) 0)))
(名 (T7 L)
    (并 (T5 L)
        (< (pt L) (minp L 5 1))
        (< (dpt L) 0)))
(名 (T8 L)
    (并 (>= (巨 (dps+ L 3)) 2)
        (>= (巨 (dvs+ L 3)) 2)))
(名 (T9 L)
    (并 (>= (巨 (dps- L 3)) 2)
        (>= (巨 (dps+ L 3)) 2)))
(名 (T10 L)
    (并 (>= (Pt L) 6)
        (= (dPt L) 0)
        (< (dpt L) 0)))
(名 (T11 L)
    (并 (<= (Pt L) 1)
        (= (dPt L) 0)
        (> (dpt L) 0)))

;; Price–Volume States
(名 (VP1 L)
    (并 (> (dPt L) 0)
        (> (dVt L) 0)))
(名 (VP2 L)
    (并 (> (dpt L) 0)
        (> (dvt L) 0)))
(名 (VP3 L)
    (并 (> (dpt L) 0)
        (< (dvt L) 0)))
(名 (VP4 L)
    (并 (> (dpt L) 0)
        (= (dvt L) 0)))
(名 (VP5 L)
    (并 (< (dPt L) 0)
        (< (dVt L) 0)))
(名 (VP6 L)
    (并 (< (dpt L) 0)
        (> (dvt L) 0)))
(名 (VP7 L)
    (并 (< (dpt L) 0)
        (< (dvt L) 0)))
(名 (VP8 L)
    (并 (<= (Pt L) 1)
        (< (dpt L) 0)
        (> (dvt L) 0)))
(名 (VP9 L)
    (并 (= (dpt L) 0)
        (> (dvt L) 0)))
(名 (VP10 L)
    (并 (= (dpt L) 0)
        (< (dvt L) 0)))
(名 (VP11 L)
    (并 (> (dpt L) 0)
        (< (dvt L) 0)))
(名 (VP12 L)
    (并 (< (dpt L) 0)
        (> (dvt L) 0)))

;; Position and Extreme States
(名 (E1 L)
    (= (Pt L) 7))
(名 (E2 L)
    (= (Pt L) 0))
(名 (E3 L)
    (>= (Pt L) 6))
(名 (E4 L)
    (<= (Pt L) 1))
(名 (E5 L)
    (= (pt L) 63))
(名 (E6 L)
    (= (pt L) 0))
(名 (E7 L)
    (>= (Vt L) 6))
(名 (E8 L)
    (<= (Vt L) 1))
(名 (E9 L)
    (= (Vt L) 7))
(名 (E10 L)
    (= (Vt L) 0))

;; Local High / Low States
(名 (E11 L)
    (> (pt L)
       (maxp L 20 1)))
(名 (E12 L)
    (< (pt L)
       (minp L 20 1)))
(名 (E13 L)
    (> (pt L)
       (maxp L 5 1)))
(名 (E14 L)
    (< (pt L)
       (minp L 5 1)))

;; Short-Term Divergence
(名 (D1 L)
    (并 (>= (Pt L) 6)
        (> (dpt L) 0)
        (< (dvt L) 0)))
(名 (D2 L)
    (并 (<= (Pt L) 1)
        (< (dpt L) 0)
        (> (dvt L) 0)))

;; Structural Divergence
(名 (D3 L)
    (令* ([L (p峰LL L)]
          [t1 (􏷜 L)] ; 距离今天较近
          [t2 (􏷛 L)])
         (并 (> (p t1) (p t2))
             (< (v t1) (v t2))
             (>= (day差  (day t2) (day t1)) 3))))
(名 (D4 L)
    (令* ([L (p谷LL L)]
          [t1 (􏷜 L)] ; 距离今天较近
          [t2 (􏷛 L)])
         (并 (< (p t1) (p t2))
             (> (v t1) (v t2))
             (>= (day差  (day t2) (day t1)) 3))))

;; Compression States
(名 (C1 L)
    (令 ([L (􏾝 L 5)])
        (并 (<= (- (maxP L) (minP L)) 1)
            (<= (- (maxp L) (minp L)) 8)
            (<= (maxV L) 2))))
(名 (C2 L)
    (令 ([L (􏾝 L 5)]
         [条件? (λ (n) (>= n 6))])
        (并 (>= (巨 (Ps 条件? L)) 4)
            (<= (- (maxp L) (minp L)) 8))))
(名 (C3 L)
    (令 ([L (􏾝 L 5)]
         [条件? (λ (n) (<= n 1))])
        (并 (>= (巨 (Ps 条件? L)) 4)
            (<= (- (maxp L) (minp L)) 8))))
(名 (C4 L)
    (令 ([L (􏾝 L 3)])
        (并 (>= (巨 (dvs+ L)) 2)
            (<= (- (maxp L) (minp L)) 8))))
(名 (C5 L)
    (令 ([L (􏾝 L 3)])
        (并 (>= (巨 (dvs- L)) 2)
            (<= (- (maxp L) (minp L)) 8))))
(名 (C6 L)
    (并 (>= (Pt L) 6)
        (>= (巨 (dvs- L 3)) 2)
        (<= (dpt L) 0)))
(名 (C7 L)
    (并 (<= (Pt L) 1)
        (>= (巨 (dvs+ L 3)) 2)
        (<= (- (maxp L 3) (minp L 3)) 8)))

;; Breakout States
(名 (BO1 L)
    (并 (> (pt L) (maxp L 5 1))
        (> (dpt L) 0)))
(名 (BO2 L)
    (并 (BO1 L) (> (dvt L) 0)))
(名 (BO3 L)
    (并 (BO2 L) (> (Vt L) (avgV L 5 1))))
(名 (BO4 L)
    (并 (< (pt L) (minp L 5 1))
        (< (dpt L) 0)))
(名 (BO5 L)
    (并 (BO4 L) (> (dpt L) 0)))
(名 (BO6 L)
    (并 (BO4 L)
        (> (dpt L) 0)
        (> (Vt L) (avgV L 5 1))))

;; Buy Signals
(名 (B1 L)
    (并 (T5 L) (BO2 L)))
(名 (B2 L)
    (并 (T5 L) (BO3 L)))
(名 (B3 L)
    (并 (>= (巨 (dps+ L 3)) 2)
        (< (dpt L) 0)
        (<= (dvt L) 0)
        (> (pt L) (minp L 3 1))))
(名 (B4 L)
    (并 (D4 L) (> (dpt L) 0)))
(名 (B5 L)
    (并 (C7 L)
        (<= (Pt L) 1)
        (> (dpt L) 0)))
(名 (B6 L)
    (并 (<= (Pt L) 1)
        (> (dpt L) 0)
        (> (dvt L) 0)))
(名 (B7 L)
    (并 (E11 L)
        (> (dpt L) 0)
        (>= (dvt L) 0)))

;; Sell Signals
(名 (S1 L)
    (并 (D1 L) (D1 (􏾘 L 0))))
(名 (S2 L)
    (并 (D3 L) (< (dpt L) 0)))
(名 (S3 L)
    (并 (>= (巨 (dps+ L 3)) 2)
        (< (dpt L) 0)
        (< (pt L) (minp L 3 1))))
(名 (S4 L) (BO5 L))
(名 (S5 L) (BO6 L))
(名 (S6 L) (C6 L))
(名 (S7 L)
    (并 (>= (Pt L) 6)
        (>= (Vt L) 6)
        (<= (dpt L) 0)))
(名 (S8 L)
    (名 (BO? L)
        (戈 (BO1 L) (BO2 L) (BO3 L)))
    (名 bos ; the days of breakouts
        (􏷑 􏷜 (􏹈 BO? (􏿴 (􏾝 L 1) (􏾝 L 2)))))
    (并 (𥦯? bos)
        (<= (pt L) (maxp bos))
        (< (dpt L) 0)))
