name: bild-ghpage
on:
  schedule:
    - cron: '1 8 * * 1-5' # this is utc time, it is 20:30 in China.  20:30 <= 12:30 + 8
  push:
    branches:
      - "master"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["stable"]
        racket-variant: ["CS"]
    name: main
    steps:
      - uses: actions/checkout@master
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - uses: Bogdanp/setup-racket@v1.5
        with:
          architecture: x64
          distribution: full # or minimal
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: install chinese lang fonts
        run: |
          #sudo apt-get -y install language-pack-zh*
          #sudo apt-get -y install chinese*
          sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei

      - name: install deps
        run: raco pkg install --auto

      - name: build *.html
        run: cp -a styles/* public/ && ./main.rkt
        env:
          CI_BUILDING: "true"
          API_DAY_IPHXR: ${{ secrets.API_DAY_IPHXR }}
          API_NTFY: ${{ secrets.API_NTFY }}

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.1.2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
